export const rotateData = [
  {
    id: 1,
    title: "冬至龍虎榜",
    status: false,
    sort: 0,
    pic: {
      mobile: {
        img: "promotion/rotate/dXoyIZ1q.png",
        url: "https://",
      },
      pc: {
        img: "promotion/rotate/aEcLjovl.png",
        url: "https://",
      },
      tablet: {
        img: "promotion/rotate/KL7RUjTW.png",
        url: "https://",
      },
    },
    link_id: 2,
    url: "",
    site: ["GPK", "GT", "OG", "LEBO-CG", "common", "LEBO", "common"],
    lang: "cn",
    edited_by: "Finn",
    start_time: "2021-12-08T00:00:00-04:00",
    end_time: "2222-01-09T00:00:00-04:00",
    created_at: "2021-12-09T02:14:45-04:00",
    updated_at: "2022-01-19T23:34:58-04:00",
  },
  {
    id: 16,
    title: "中國新春龍虎榜",
    status: false,
    sort: 0,
    pic: {
      mobile: {
        img: "promotion/rotate/zcbqPbHQ.png",
        url: "https://",
      },
      pc: {
        img: "promotion/rotate/kkM9cobk.png",
        url: "https://",
      },
      tablet: {
        img: "promotion/rotate/sLDxfOrB.png",
        url: "https://",
      },
    },
    link_id: 2,
    url: "",
    site: [],
    lang: "cn",
    edited_by: "Finn",
    start_time: "2022-01-19T00:00:00-04:00",
    end_time: "2042-01-20T00:00:00-04:00",
    created_at: "2022-01-19T23:37:39-04:00",
    updated_at: "2022-03-03T02:07:24-04:00",
  },
  {
    id: 18,
    title: "中國春神龍虎榜",
    status: false,
    sort: 0,
    pic: {
      mobile: {
        img: "promotion/rotate/BfABBH39.png",
        url: "https://",
      },
      pc: {
        img: "promotion/rotate/OVLxMqst.png",
        url: "https://",
      },
      tablet: {
        img: "promotion/rotate/VGnxdJlM.png",
        url: "https://",
      },
    },
    link_id: 6,
    url: "",
    site: [],
    lang: "cn",
    edited_by: "Finn",
    start_time: "2022-03-03T00:00:00-04:00",
    end_time: "2022-04-15T00:00:00-04:00",
    created_at: "2022-03-03T02:08:58-04:00",
    updated_at: "2022-04-13T21:39:49-04:00",
  },
  {
    id: 19,
    title: "中國周年慶龍虎榜",
    status: true,
    sort: 0,
    pic: {
      mobile: {
        img: "promotion/rotate/7BcD1KtK.png",
        url: "https://",
      },
      pc: {
        img: "promotion/rotate/mybzw9Sd.png",
        url: "https://",
      },
      tablet: {
        img: "promotion/rotate/ok7Wh7Es.png",
        url: "https://",
      },
    },
    link_id: 2,
    url: "",
    site: ["GPK", "GT", "LEBO", "OG", "LEBO-CG", "common"],
    lang: "cn",
    edited_by: "Finn",
    start_time: "2022-04-13T00:00:00-04:00",
    end_time: "2022-06-02T00:00:00-04:00",
    created_at: "2022-04-13T21:42:07-04:00",
    updated_at: "2022-04-13T21:42:31-04:00",
  },
  {
    id: 2,
    title: "實況視頻",
    status: true,
    sort: 1,
    pic: {
      mobile: {
        img: "promotion/rotate/GRbVG7dv.png",
        url: "https://",
      },
      pc: {
        img: "promotion/rotate/b7mPkrhU.png",
        url: "https://",
      },
      tablet: {
        img: "promotion/rotate/wLM0Lylv.png",
        url: "https://",
      },
    },
    link_id: 6,
    url: "",
    site: ["GPK", "GT", "LEBO", "OG", "LEBO-CG", "common", "common"],
    lang: "cn",
    edited_by: "Finn",
    start_time: "2021-06-30T00:00:00-04:00",
    end_time: "2221-07-30T00:00:00-04:00",
    created_at: "2021-12-09T02:14:45-04:00",
    updated_at: "2022-03-03T02:08:58-04:00",
  },
  {
    id: 17,
    title: "元宵押碼王",
    status: false,
    sort: 1,
    pic: {
      mobile: {
        img: "promotion/rotate/0ggNAS25.png",
        url: "https://",
      },
      pc: {
        img: "promotion/rotate/s4o6g6ue.png",
        url: "https://",
      },
      tablet: {
        img: "promotion/rotate/oJ2yrWfw.png",
        url: "https://",
      },
    },
    link_id: 2,
    url: "",
    site: [],
    lang: "cn",
    edited_by: "Finn",
    start_time: "2022-02-09T00:00:00-04:00",
    end_time: "2042-02-09T00:00:00-04:00",
    created_at: "2022-02-09T02:06:56-04:00",
    updated_at: "2022-03-03T02:07:27-04:00",
  },
  {
    id: 3,
    title: "爆款遊戲-跑跑愛麗絲",
    status: true,
    sort: 2,
    pic: {
      mobile: {
        img: "promotion/rotate/LsBBiOxH.png",
        url: "https://",
      },
      pc: {
        img: "promotion/rotate/ySGFt5DN.png",
        url: "https://",
      },
      tablet: {
        img: "promotion/rotate/fIhPjlo2.png",
        url: "https://",
      },
    },
    link_id: 5,
    url: "4",
    site: ["GPK", "GT", "LEBO", "OG", "LEBO-CG", "common", "common"],
    lang: "cn",
    edited_by: "Finn",
    start_time: "2021-06-11T00:00:00-04:00",
    end_time: "2221-07-11T00:00:00-04:00",
    created_at: "2021-12-09T02:14:45-04:00",
    updated_at: "2022-03-03T02:08:58-04:00",
  },
  {
    id: 4,
    title: "爆款遊戲-雷神",
    status: true,
    sort: 3,
    pic: {
      mobile: {
        img: "promotion/rotate/3DQAqmW8.png",
        url: "https://",
      },
      pc: {
        img: "promotion/rotate/ahGRCUsC.png",
        url: "https://",
      },
      tablet: {
        img: "promotion/rotate/q41J7aVN.png",
        url: "https://",
      },
    },
    link_id: 5,
    url: "1",
    site: ["GPK", "GT", "LEBO", "OG", "LEBO-CG", "common", "common"],
    lang: "cn",
    edited_by: "Finn",
    start_time: "2021-06-11T00:00:00-04:00",
    end_time: "2221-07-11T00:00:00-04:00",
    created_at: "2021-12-09T02:14:45-04:00",
    updated_at: "2022-03-03T02:08:58-04:00",
  },
  {
    id: 5,
    title: "派彩指數報好路 讓你出分有譜",
    status: true,
    sort: 4,
    pic: {
      mobile: {
        img: "promotion/rotate/MZnSnufU.png",
        url: "https://",
      },
      pc: {
        img: "promotion/rotate/XJ9sZoKP.png",
        url: "https://",
      },
      tablet: {
        img: "promotion/rotate/yLIfovVL.png",
        url: "https://",
      },
    },
    link_id: 1,
    url: "76",
    site: ["GPK", "GT", "LEBO", "OG", "LEBO-CG", "common", "common"],
    lang: "cn",
    edited_by: "Finn",
    start_time: "2020-02-13T00:00:00-04:00",
    end_time: "2220-03-13T00:00:00-04:00",
    created_at: "2021-12-09T02:14:45-04:00",
    updated_at: "2022-03-03T02:08:58-04:00",
  },
];

export const menu = {
  editor: [
    {
      name: "輪播圖列表",
      route: "rotate-list",
    },
    {
      name: "跑馬燈列表",
      route: "announcement-list",
    },
    {
      name: "影片列表",
      route: "video",
    },
    {
      name: "最新報導",
      route: "news",
    },
    {
      name: "活動列表",
      route: "activities",
    },
    {
      name: "浮動廣告列表",
      route: "ad-float",
    },
    {
      name: "彈窗廣告列表",
      route: "ad-popup",
    },
    {
      name: "爆款遊戲",
      route: "special-game",
    },
    {
      name: "標籤管理",
      route: "category",
    },
    {
      name: "程式碼編輯",
      route: "code-edit",
    },
  ],
  management: [
    {
      name: "維護開關",
      route: "maintain",
    },
    {
      name: "使用者管理",
      route: "user-management",
    },
  ],
};

export const langData = [
  {
    id: 1,
    lang: "cn",
    name: "简中",
  },
  {
    id: 2,
    lang: "en",
    name: "English",
  },
  {
    id: 3,
    lang: "vn",
    name: "Việt nam",
  },
  {
    id: 4,
    lang: "th",
    name: "ประเทศไทย",
  },
];

export const specialGameData = [
  {
    id: 1,
    title: "雷神",
    lang: "cn",
    status: true,
    sort: 0,
    pic: {
      flag: {
        img: "promotion/special_game/M0zLplWQ.png",
        url: "https://",
      },
      mobile: {
        img: "promotion/special_game/xsCwiOzy.jpg",
        url: "https://",
      },
      pc: {
        img: "promotion/special_game/f00xXcQy.jpeg",
        url: "https://",
      },
      tablet: {
        img: "promotion/special_game/FCCZK7sh.jpeg",
        url: "https://",
      },
    },
    link_id: 3,
    url: "182",
    site: ["GT", "GPK", "LEBO", "OG", "LEBO-CG", "公共推廣網", "common"],
    edited_by: "kyrie",
    created_at: "2021-12-09 02:14:45",
    updated_at: "2021-12-29 03:04:06",
  },
  {
    id: 4,
    title: "跑跑爱丽丝",
    lang: "cn",
    status: true,
    sort: 1,
    pic: {
      flag: {
        img: "promotion/special_game/5L5RtIFx.png",
        url: "https://",
      },
      mobile: {
        img: "promotion/special_game/aiJuAiBj.jpeg",
        url: "https://",
      },
      pc: {
        img: "promotion/special_game/iL0KMWSh.jpeg",
        url: "https://",
      },
      tablet: {
        img: "promotion/special_game/83GCizCw.jpeg",
        url: "https://",
      },
    },
    link_id: 3,
    url: "guide_lobby",
    site: ["GT", "LEBO", "OG", "LEBO-CG", "GPK", "common"],
    edited_by: "kyrie",
    created_at: "2021-12-09 02:14:45",
    updated_at: "2021-12-29 03:04:06",
  },
  {
    id: 7,
    title: "一炮捕魚",
    lang: "cn",
    status: true,
    sort: 2,
    pic: {
      flag: {
        img: "promotion/special_game/g0nOBzdh.png",
        url: "https://",
      },
      mobile: {
        img: "promotion/special_game/6R4pLiSN.jpg",
        url: "https://",
      },
      pc: {
        img: "promotion/special_game/3HiYcHik.jpeg",
        url: "https://",
      },
      tablet: {
        img: "promotion/special_game/gXV389YH.jpeg",
        url: "https://",
      },
    },
    link_id: 3,
    url: "AT01",
    site: ["GPK", "GT", "LEBO", "OG", "LEBO-CG", "公共推廣網", "common"],
    edited_by: "kyrie",
    created_at: "2021-12-09 02:14:45",
    updated_at: "2021-12-29 03:04:06",
  },
];

export const guideListData = [
  {
    game_id: "1",
    type: 1,
    name: {
      cn: "钻石水果王",
      en: "Fruit King",
      id: "Raja Buah",
      ko: "후르츠 킹",
      th: "ราชาผลไม้",
      vn: "Vua trái cây",
    },
    icon: {
      cn: "https://+GULTJTKf.png",
      en: "https://+M5k8fcBE.png",
      es: "https://+XXU4wExW.png",
      id: "https://+n9LbVmzW.png",
      ja: "https://+gnzN8fII.png",
      ko: "https://+j6DAWQOP.png",
      th: "https://+PNiWqzWi.png",
      vn: "https://+yFBWtMlz.png",
    },
    create_at: "2019-11-28 09:06:01",
  },
  {
    game_id: "2",
    type: 1,
    name: {
      cn: "棋圣",
      en: "God Of Chess",
      id: "Dewa Catur",
      ko: "갓 오브 체스",
      th: "เทพหมากรุก",
      vn: "Chúa cờ vua",
    },
    icon: {
      cn: "https://+fHm7VSAD.png",
      en: "https://+xz7zurdV.png",
      id: "https://+GoVtoHps.png",
      ko: "https://+NcQ6Cn4S.png",
      th: "https://+X9lMaVam.png",
      vn: "https://+461YX3YC.png",
    },
    create_at: "2019-11-28 09:06:30",
  },
  {
    game_id: "3",
    type: 1,
    name: {
      cn: "血之吻",
      en: "Vampire Kiss",
      id: "Ciuman Vampir",
      ko: "뱀파이어 키스",
      th: "รอยจูบผี",
      vn: "Nụ hôn ma cà rồng",
    },
    icon: {
      cn: "https://+IYRyHP9L.PNG",
      en: "https://+j6yXzx7I.png",
      es: "https://+G7IRMjnG.png",
      id: "https://+H2H3wAO6.png",
      ja: "https://+Qtn7m8qG.png",
      ko: "https://+Un86trxd.png",
      th: "https://+L9UVr7yB.png",
      vn: "https://+MTP5qW7n.png",
    },
    create_at: "2019-11-28 09:06:33",
  },
  {
    game_id: "4",
    type: 1,
    name: {
      cn: "森林泰后",
      en: "Wild Tarzan",
      id: "Tarzan Liar",
      ko: "와일드 타잔",
      th: "ทาร์ซานป่า",
      vn: "Tarzan hoang dã",
    },
    icon: {
      cn: "https://+CYmSghDM.png",
      en: "https://+0IT0ytjx.png",
      es: "https://+02DHBCsF.png",
      id: "https://+gZ4UqrCp.png",
      ja: "https://+KNc8gu65.png",
      ko: "https://+XDmG24G6.png",
      th: "https://+hTWBcppN.png",
      vn: "https://+vaomlFCb.png",
    },
    create_at: "2019-11-28 09:06:36",
  },
  {
    game_id: "5",
    type: 1,
    name: {
      cn: "金大款",
      en: "Mr. Rich",
      id: "Tn. Kaya",
      ko: "미스터 리치",
      th: "ท่านเศรษฐี",
      vn: "Ông Rich",
    },
    icon: {
      cn: "https://+cPsyO0gi.png",
      en: "https://+p6IdSgsl.png",
      es: "https://+wMU7KSMH.png",
      id: "https://+B9AFR4SN.png",
      ja: "https://+h1PqsGNX.png",
      ko: "https://+ZvFj4ZtI.png",
      th: "https://+c1daTCOR.png",
      vn: "https://+ERUzQlIO.png",
    },
    create_at: "2019-11-28 09:07:10",
  },
  {
    game_id: "7",
    type: 1,
    name: {
      cn: "跳起来",
      en: "Rave Jump",
      es: "Salto rave",
      id: "Rave Jump",
      ja: "レイヴ・ジャンプ",
      ko: "레이브 점프",
      th: "เรพจั๊ม",
      vn: "Mê sảng",
    },
    icon: {
      cn: "https://+jYRsEITB.png",
      en: "https://+20x1jSLJ.png",
      es: "https://+wNdJq2pa.png",
      id: "https://+20x1jSLJ.png",
      ja: "https://+THPDPk90.png",
      ko: "https://+UCqQWuYi.png",
      th: "https://+HUsGaOsF.png",
      vn: "https://+fnO6eZVv.png",
    },
    create_at: "2019-11-28 09:07:17",
  },
  {
    game_id: "8",
    type: 1,
    name: {
      cn: "甜蜜蜜",
      en: "So Sweet",
      id: "Manis Sekali",
      ko: "소 스위트",
      th: "เถี่ยนมี่มี่",
      vn: "Thật ngọt ngào",
    },
    icon: {
      cn: "https://+NyOKrOCY.png",
      en: "https://+l2pXvnE2.png",
      es: "https://+BsaTfoVf.png",
      id: "https://+YH556Uak.png",
      ja: "https://+XBsENH23.png",
      ko: "https://+25T0rnJa.png",
      th: "https://+naqsNr4k.png",
      vn: "https://+nJ4p5nva.png",
    },
    create_at: "2019-11-28 09:07:22",
  },
  {
    game_id: "9",
    type: 1,
    name: {
      cn: "钟馗运财",
      en: "Zhong Kui",
      es: "Zhong Kui",
      id: "Zhong Kui",
      ja: "鍾馗様",
      ko: "종규",
      th: "จงขุ่ย",
      vn: "Zhong Kui",
    },
    icon: {
      cn: "https://+sG5uDWK2.png",
      en: "https://+Qp8HJX37.png",
      es: "https://+WJJL20fL.png",
      id: "https://+Qp8HJX37.png",
      ja: "https://+ok3covU1.png",
      ko: "https://+kOaCPNCR.png",
      "pt-BR": "https://+Qp8HJX37.png",
      th: "https://+f5U3ACUA.png",
      vn: "https://+Qp8HJX37.png",
    },
    create_at: "2019-11-28 09:07:27",
  },
  {
    game_id: "10",
    type: 1,
    name: {
      cn: "五福临门",
      en: "Lucky Bats",
      es: "Bates de la suerte",
      id: "Kelelawar Mujur",
      ja: "五福臨門",
      ko: "럭키 뱃",
      th: "ลัคกี้ แบท",
      vn: "Chú dơi may mắn",
    },
    icon: {
      cn: "https://+xjXVC7kS.png",
      en: "https://+0s2JAojt.png",
      es: "https://+JdlR5FOe.png",
      id: "https://+ID0pXZZ9.png",
      ja: "https://+XA73Xclu.png",
      ko: "https://+7j0UJdnI.png",
      "pt-BR": "https://+CpENkM1j.png",
      th: "https://+d6yM8pio.png",
      vn: "https://+HIAVzbzn.png",
    },
    create_at: "2019-11-28 09:07:29",
  },
  {
    game_id: "12",
    type: 1,
    name: {
      cn: "金玉满堂",
      en: "Treasure House",
      id: "Rumah Harta Karun",
      ko: "트래져 하우스",
      th: "บ้านขุมทรัพย์",
      vn: "Kho báu",
    },
    icon: {
      cn: "https://+WPv4pxTp.png",
      en: "https://+41REF4m9.png",
      es: "https://+UTkeHenV.png",
      id: "https://+6IA9SGeT.png",
      ja: "https://+byTXPFTK.png",
      ko: "https://+FfwEotwU.png",
      "pt-BR": "https://+2WEmp79q.png",
      th: "https://+tRaMgyN0.png",
      vn: "https://+eLAQW3CB.png",
    },
    create_at: "2019-11-28 09:07:35",
  },
  {
    game_id: "13",
    type: 1,
    name: {
      cn: "樱花妹子",
      en: "Sakura Legend",
      id: "Legenda Sakura",
      ko: "사쿠라 레전드",
      th: "ตำนานซากุระ",
      vn: "Truyền thuyết Sakura",
    },
    icon: {
      cn: "https://+ZKhl4QNC.png",
      en: "https://+V4xFcXeB.png",
      es: "https://+JdtXJ0TD.png",
      id: "https://+KWlIzzo5.png",
      ja: "https://+zlBI0SWB.png",
      ko: "https://+bSt9tFZ6.png",
      "pt-BR": "https://+i1402bAD.png",
      th: "https://+T9SE7rwO.png",
      vn: "https://+m9FESLu7.png",
    },
    create_at: "2019-11-28 09:07:37",
  },
  {
    game_id: "15",
    type: 1,
    name: {
      cn: "金鸡报喜",
      en: "GuGuGu",
      es: "Quiquiriqui",
      id: "GuGuGu",
      ko: "GuGuGu",
      th: "ไก่ทองประกาศข่างดี",
      vn: "GuGuGu",
    },
    icon: {
      cn: "https://+IFeEfAq5.png",
      en: "https://+R7qHNfZf.png",
      es: "https://+gEDfUSpx.png",
      id: "https://+R7qHNfZf.png",
      ja: "https://+GEDzEHUW.png",
      ko: "https://+xmZwseuj.png",
      "pt-BR": "https://+ImqP4Soz.png",
      th: "https://+Hlvjv90i.png",
      vn: "https://+rOpGK0Mc.png",
    },
    create_at: "2019-11-28 09:07:41",
  },
  {
    game_id: "16",
    type: 1,
    name: {
      cn: "五行",
      en: "Super5",
      id: "Super5",
      ko: "오행",
      th: "5 ธาตุสะท้านภพ",
      vn: "Super5",
    },
    icon: {
      cn: "https://+97Qmab3q.png",
      en: "https://+P97Remip.png",
      es: "https://+tsUnJrJM.png",
      id: "https://+TS9TeT0D.png",
      ja: "https://+jNpqTB43.png",
      ko: "https://+YEdaUWJs.png",
      "pt-BR": "https://+pN0CVzwB.png",
      th: "https://+92QCW7t8.png",
      vn: "https://+rxocJXju.png",
    },
    create_at: "2019-11-28 09:07:44",
  },
  {
    game_id: "17",
    type: 1,
    name: {
      cn: "祥狮献瑞",
      en: "Great Lion",
      id: "Singa Besar",
      ko: "그레이트 라이언",
      th: "สิงโตให้มงคล",
      vn: "Sư tử lớn",
    },
    icon: {
      cn: "https://+oJmY6TtD.png",
      en: "https://+xekMMfqm.png",
      es: "https://+xekMMfqm.png",
      id: "https://+o1RRl8Vq.png",
      ja: "https://+xekMMfqm.png",
      ko: "https://+q9t1Jc9f.png",
      "pt-BR": "https://+xekMMfqm.png",
      th: "https://+7rrf1HqY.png",
      vn: "https://+1g5shFqd.png",
    },
    create_at: "2019-11-28 09:07:47",
  },
  {
    game_id: "19",
    type: 1,
    name: {
      cn: "风火轮",
      en: "Hot Spin",
      id: "Putaran Seru",
      ko: "핫 스핀",
      th: "ล้อไฟลม",
      vn: "Quay nóng",
    },
    icon: {
      cn: "https://+yXVRx7yl.png",
      en: "https://+JjppyVxd.png",
      es: "https://+4bzeXy2d.png",
      id: "https://+qOsHQWYn.png",
      ja: "https://+vt2AKbq9.png",
      ko: "https://+preJcmm2.png",
      "pt-BR": "https://+aiXliwiH.png",
      th: "https://+yT4DR0JD.png",
      vn: "https://+ImqHrvvU.png",
    },
    create_at: "2019-11-28 09:07:54",
  },
  {
    game_id: "21",
    type: 1,
    name: {
      cn: "野狼传说",
      en: "Big Wolf",
      id: "Legenda Serigala",
      ko: "빅 울프",
      th: "ตำนานหมาป่า",
      vn: "Truyền thuyết chó sói",
    },
    icon: {
      cn: "https://+Eb4SXqbJ.png",
      en: "https://+A6vuOK7r.png",
      es: "https://+A6vuOK7r.png",
      id: "https://+sqLfuQpo.png",
      ja: "https://+A6vuOK7r.png",
      ko: "https://+VicgpK0A.png",
      "pt-BR": "https://+A6vuOK7r.png",
      th: "https://+dM8h4fuh.png",
      vn: "https://+qV3JbJhx.png",
    },
    create_at: "2019-12-13 10:23:50",
  },
  {
    game_id: "22",
    type: 1,
    name: {
      cn: "庶务西游二课",
      en: "Monkey Office Legend",
      id: "Legenda Pejabat Kera",
      ko: "몽키 오피스 레전드",
      th: "ไซอิ๋ว",
      vn: "Truyền thuyết ngôi nhà khỉ",
    },
    icon: {
      cn: "https://+Y60pZND7.png",
      en: "https://+ECTGAb9g.png",
      es: "https://+ZMZBgot6.png",
      id: "https://+wEO3XJFG.png",
      ja: "https://+SQkShq6Y.png",
      ko: "https://+bOlirHNG.png",
      "pt-BR": "https://+QP8bGkzL.png",
      th: "https://+nO6b7TnM.png",
      vn: "https://+3nSvEutB.png",
    },
    create_at: "2019-12-13 10:24:41",
  },
  {
    game_id: "26",
    type: 1,
    name: {
      cn: "777",
      en: "777",
      es: "777",
      id: "777",
      ko: "777",
      th: "777",
      vn: "777",
    },
    icon: {
      cn: "https://+fEXruAg3.png",
      en: "https://+TLC28bsL.png",
      es: "https://+TkcuHFim.png",
      id: "https://+TLC28bsL.png",
      ko: "https://+K4hdpKaU.png",
      th: "https://+TLC28bsL.png",
      vn: "https://+TLC28bsL.png",
    },
    create_at: "2019-12-13 10:28:43",
  },
  {
    game_id: "29",
    type: 1,
    name: {
      cn: "水世界",
      en: "WaterWorld",
      id: "dunia air",
      ko: "워터월드",
      th: "เวิลด์น้ำ",
      vn: "Thế giới nước",
    },
    icon: {
      cn: "https://+TZov3J3v.png",
      en: "https://+GfVEmotT.png",
      es: "https://+7QDGl1Lu.png",
      id: "https://+rLf6HPuc.png",
      ja: "https://+oUtcBBWJ.png",
      ko: "https://+JE4Nmmno.png",
      "pt-BR": "https://+qv7lybJ0.png",
      th: "https://+3OglqZwa.png",
      vn: "https://+shPGfs8P.png",
    },
    create_at: "2019-12-18 03:43:31",
  },
  {
    game_id: "31",
    type: 1,
    name: {
      cn: "武圣",
      en: "God of War",
      es: "Dios de la Guerra",
      id: "Dewa Perang",
      ja: "ゴッド・オブ・ウォー",
      ko: "갓 오브 워",
      th: "สงครามเทพ",
      vn: "Thần chiến tranh",
    },
    icon: {
      cn: "https://+EDBYBPEj.png",
      en: "https://+XdsdCyXK.png",
      es: "https://+wAi4mwaL.png",
      id: "https://+i23PtwB3.png",
      ja: "https://+NZpS1jVa.png",
      ko: "https://+WlqG54hK.png",
      "pt-BR": "https://+nMTiAy4u.png",
      th: "https://+nykvUWR4.png",
      vn: "https://+LMXR1wkS.png",
    },
    create_at: "2019-12-18 03:53:20",
  },
  {
    game_id: "32",
    type: 1,
    name: {
      cn: "通天神探狄仁杰",
      en: "Detective Dee",
      id: "Dee Detektif",
      ko: "명탐정 디",
      th: "นักสืบคดี",
      vn: "Thám tử Dee",
    },
    icon: {
      cn: "https://+oQNgK0Al.png",
      en: "https://+7SVoxQzw.png",
      es: "https://+7kzonrCQ.png",
      id: "https://+slkdHXpE.png",
      ja: "https://+MTHKYmE1.png",
      ko: "https://+ertqjHEq.png",
      "pt-BR": "https://+wosJFuKR.png",
      th: "https://+1usAeEcg.png",
      vn: "https://+crr0CZTU.png",
    },
    create_at: "2019-12-18 06:03:55",
  },
  {
    game_id: "33",
    type: 1,
    name: {
      cn: "火烧连环船",
      en: "Fire Chibi",
      id: "Chibi Api",
      ko: "파이어 치비",
      th: "เปลวไฟแห่งความร่ำรวย",
      vn: "Ngọn lửa Chibi",
    },
    icon: {
      cn: "https://+WyhSnGQg.png",
      en: "https://+uxeVBYcn.png",
      es: "https://+Aafz6q5T.png",
      id: "https://+5ZIa0eA8.png",
      ja: "https://+7ixJmVLu.png",
      ko: "https://+Riw3No2R.png",
      "pt-BR": "https://+Tx4FZklN.png",
      th: "https://+s3sdzGvH.png",
      vn: "https://+tNChvkgw.png",
    },
    create_at: "2019-12-18 06:06:22",
  },
  {
    game_id: "34",
    type: 1,
    name: {
      cn: "地鼠战役",
      en: "Gophers War",
      id: "Perang Tikus",
      ko: "고퍼 워",
      th: "สงครามหนู",
      vn: "Chiến tranh chuột túi",
    },
    icon: {
      cn: "https://+GZosaUcT.png",
      en: "https://+x5yPsK1M.png",
      es: "https://+6EGFCitl.png",
      id: "https://+N1KcJl3Q.png",
      ja: "https://+ohT1Z7rt.png",
      ko: "https://+IHRIeSDE.png",
      "pt-BR": "https://+yKM5JKnM.png",
      th: "https://+HH8KdeLC.png",
      vn: "https://+mh68osSs.png",
    },
    create_at: "2019-12-18 06:09:42",
  },
  {
    game_id: "35",
    type: 1,
    name: {
      cn: "疯狂哪吒",
      en: "Crazy Nuozha",
      id: "CRAZY NUOZHA",
      ko: "나타",
      th: "นาจาคลั่ง",
      vn: "CRAZY NUOZHA",
    },
    icon: {
      cn: "https://+7lg3EUWz.png",
      en: "https://+UFUdbq0z.png",
      id: "https://+UFUdbq0z.png",
      ko: "https://+azsNHgqb.png",
      th: "https://+DJuzGoGU.png",
      vn: "https://+zTQVeo4b.png",
    },
    create_at: "2019-12-18 06:11:48",
  },
];

export const newsListData = [
  {
    id: 319,
    title: "花好月圆人团圆，吃饼拿奖乐开怀！奖金10888，究竟会奖落谁家？",
    description: "",
    content:
      '<p class="ql-align-justify">中秋佳节到，看着又大又圆的月亮，</p><p class="ql-align-justify">让人不禁想念起…那每到中秋节就必吃的美味月饼！</p><p class="ql-align-justify">这么温馨的日子，CQ9当然也为各位准备了好礼～</p><p class="ql-align-justify">只要达到指定押码，就能兑换带有丰富奖金的四种月饼，</p><p class="ql-align-justify">打开就有奖，最高单颗奖金10888！数量有限，送完为止～</p><p class="ql-align-justify">吃了就能感受到幸福与满足的神奇月饼，只在CQ9！</p><p class="ql-align-justify">&nbsp;</p><p class="ql-align-justify">▶ 活动时间</p><p class="ql-align-justify">北京时间 9/16 12:00pm - 10/14 12:00pm</p><p class="ql-align-justify">&nbsp;</p><p class="ql-align-justify">▶ 参与方式</p><p class="ql-align-justify">活动期间内，在【CQ9】游戏下注，累积到指定码量，即可兑换来自玉兔的神秘惊喜！</p><p class="ql-align-justify">*因游戏性特殊，CQ9真人及CQ9彩票未参与此次活动</p><p class="ql-align-justify">&nbsp;</p><p class="ql-align-justify">▶ 活动规则</p><p class="ql-align-justify">四种藏金月饼：月饼、银饼、金饼、玉兔饼，</p><p class="ql-align-justify">累积到指定码量，就能领取对应饼种～</p><p class="ql-align-justify">即时派发奖金，不用苦等一周结算！</p><p class="ql-align-justify">每日月饼数量有限，要领要快呦！</p><p class="ql-align-justify">&nbsp;</p><p class="ql-align-justify">9/16 中午12点活动开跑，一起来体验吃饼的快乐！</p><p class="ql-align-justify">&nbsp;</p><p><br></p>',
    pic: {
      img: "promotion/news/sljD1XIk.png",
      url: "https://",
    },
    category_id: 11,
    status: true,
    site: ["GPK", "GT", "LEBO", "OG", "LEBO-CG", "common"],
    start_time: "2021-09-09T00:00:00-04:00",
    end_time: "2221-09-30T00:00:00-04:00",
    edited_by: "Finn",
    created_at: "2021-12-16T22:06:40-04:00",
    updated_at: "2021-12-16T22:32:25-04:00",
  },
  {
    id: 320,
    title: "玉兔降临，打码换月饼～活动今日开跑！看我一饼拿下10888！",
    description: "",
    content:
      '<p class="ql-align-justify"><img src="https://promotion/news/xfEh2N83.jpg"></p><p class="ql-align-justify">【打码换月饼】活动于今日中午12点正式开跑啦～</p><p class="ql-align-justify"><span style="color: red;">&nbsp;</span></p><p class="ql-align-justify">四种藏金月饼，每个口味都暗藏不同的惊喜，</p><p class="ql-align-justify">只要达到指定押码即可兑换，单颗最高10888，总奖超过150万！</p><p class="ql-align-justify">奖金即时派发，一个月的时间让你吃饱吃满～</p><p class="ql-align-justify">每日数量有限，晚来你就没得吃啦！</p><p class="ql-align-justify"><span style="color: red;">&nbsp;</span></p><p class="ql-align-justify"><strong>活动时间：北京时间 9/16 12:00pm - 10/14 12:00pm</strong></p><p class="ql-align-justify">&nbsp;</p><p class="ql-align-justify">活动期间内，在【CQ9】游戏下注，累积到指定码量，即可兑换来自玉兔的神秘惊喜！</p><p class="ql-align-justify">即领即送，打开就有钱！每日数量有限，送完为止！</p><p class="ql-align-justify"><strong style="color: red;">&nbsp;</strong></p><p><img src="https://promotion/news/0uEqkEjB.PNG"></p><p class="ql-align-justify"><strong>&nbsp;</strong></p><p class="ql-align-justify"><strong>&nbsp;</strong></p><p class="ql-align-justify"><strong>★</strong>注意事项</p><p class="ql-align-justify">1.&nbsp;因游戏性特殊，<strong>CQ9真人</strong>及<strong>CQ9彩票</strong>将不参与此次活动，敬请见谅。&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p><p class="ql-align-justify">2.&nbsp;活动时间以系统公告为主。</p><p class="ql-align-justify">3.&nbsp;每日月饼数量有限，送完为止。</p><p class="ql-align-justify">4.&nbsp;玩家累积总押码、已领取奖金、每日剩余数量，每5分钟更新一次。</p><p class="ql-align-justify">5.&nbsp;开奖纪录保留兩周。</p><p class="ql-align-justify">6.&nbsp;奖金将于领取当下派发，敬请玩家留意帐户余额。</p><p class="ql-align-justify">7.&nbsp;如遇特殊状况，本公司保有修改、变更或暂停本活动之权利。</p><p class="ql-align-justify">8.&nbsp;本活动所产生的任何相关异议及问题，本公司保有最终解释权。</p><p class="ql-align-justify"><br></p>',
    pic: {
      img: "promotion/news/akSvrcy8.png",
      url: "https://",
    },
    category_id: 11,
    status: true,
    site: ["GPK", "GT", "LEBO", "OG", "LEBO-CG", "common"],
    start_time: "2021-09-16T00:00:00-04:00",
    end_time: "2221-09-30T00:20:00-04:00",
    edited_by: "steve",
    created_at: "2021-12-16T22:06:40-04:00",
    updated_at: "2021-12-16T22:32:25-04:00",
  },
];

export const marqueeData = [
  {
    id: 1,
    title: "「火烧连环船2」你玩过了吗？热门游戏全新改版，锁定百搭赢四千倍！",
    lang: "cn",
    url: "188",
    category_id: 5,
    link_id: 1,
    status: true,
    site: ["GPK", "GT", "LEBO", "OG", "LEBO-CG", "common"],
    start_time: "2019-05-28T00:00:00-04:00",
    end_time: "2219-06-28T00:00:00-04:00",
    edited_by: "kyrie",
    created_at: "2021-12-09T02:14:45-04:00",
    updated_at: "2021-12-28T05:56:12-04:00",
  },
  {
    id: 2,
    title: "1,440,500派彩就开在「鸿福齐天」？超猛过程让你落下巴！",
    lang: "cn",
    url: "189",
    category_id: 5,
    link_id: 1,
    status: true,
    site: ["GPK", "GT", "LEBO", "OG", "LEBO-CG"],
    start_time: "2019-05-30T00:00:00-04:00",
    end_time: "2029-06-30T00:00:00-04:00",
    edited_by: "",
    created_at: "2021-12-09T02:14:45-04:00",
    updated_at: "2022-01-05T05:06:25-04:00",
  },
  {
    id: 3,
    title: "直式屏幕顺畅杀敌，「一炮捕鱼」击败神龙大BOSS独赢500倍超狂大奖！！",
    lang: "cn",
    url: "190",
    category_id: 5,
    link_id: 1,
    status: true,
    site: ["GPK", "GT", "LEBO", "OG", "LEBO-CG"],
    start_time: "2019-06-04T00:00:00-04:00",
    end_time: "2029-07-04T00:00:00-04:00",
    edited_by: "",
    created_at: "2021-12-09T02:14:45-04:00",
    updated_at: "2022-01-05T05:07:34-04:00",
  },
  {
    id: 5,
    title: "6X5超巨盘面开出13625倍？「飞天财神」搞的啦！",
    lang: "cn",
    url: "193",
    category_id: 5,
    link_id: 1,
    status: false,
    site: ["GPK", "GT", "LEBO", "OG", "LEBO-CG"],
    start_time: "2019-06-14T00:00:00-04:00",
    end_time: "2219-07-14T00:00:00-04:00",
    edited_by: "",
    created_at: "2021-12-09T02:14:45-04:00",
    updated_at: "2022-01-05T05:08:55-04:00",
  },
];

export const categoryData = {
  marquee: {
    type_id: 1,
    type_name: "跑马灯",
    category: [
      {
        id: 2,
        name: "即时大奖",
        edited_by: "kyrie",
      },
      {
        id: 3,
        name: "活动公告",
        edited_by: "Neil",
      },
      {
        id: 5,
        name: "游戏推广",
        edited_by: "kyrie",
      },
      {
        id: 7,
        name: "新闻热播",
        edited_by: "rita",
      },
      {
        id: 10,
        name: "系统维护",
        edited_by: "kyrie",
      },
      {
        id: 25,
        name: "优惠活动",
        edited_by: "kyrie",
      },
    ],
  },
  news: {
    type_id: 2,
    type_name: "最新报导",
    category: [
      {
        id: 11,
        name: "活动公告",
        edited_by: "Neil",
      },
      {
        id: 13,
        name: "每周战报",
        edited_by: "Neil",
      },
      {
        id: 15,
        name: "游戏百科",
        edited_by: "Neil",
      },
      {
        id: 17,
        name: "站台公告",
        edited_by: "Neil",
      },
      {
        id: 19,
        name: "热门焦点",
        edited_by: "kyrie",
      },
    ],
  },
};

export const videoData = [
  {
    id: 48,
    title: "消消乐游戏会开大奖？万倍大奖实例带你來看",
    pic: {
      url: "https://",
      img: "",
    },
    url: {
      link: "promotion/video/LW3bWcaA.mp4",
      domain: "https://",
    },
    internal: true,
    status: true,
    site: ["GPK", "GT", "LEBO", "OG", "LEBO-CG", "common"],
    edited_by: "rita",
    created_at: "2021-01-28T02:43:44-04:00",
    updated_at: "2021-12-16T22:34:30-04:00",
  },
  {
    id: 50,
    title: "3626倍舞池奖，蹦迪没阻碍",
    pic: {
      url: "https://",
      img: "",
    },
    url: {
      link: "promotion/video/8Xw02kT3.mp4",
      domain: "https://",
    },
    internal: true,
    status: true,
    site: ["GPK", "GT", "LEBO", "OG", "LEBO-CG", "common"],
    edited_by: "rita",
    created_at: "2021-01-28T02:49:38-04:00",
    updated_at: "2021-12-16T22:34:30-04:00",
  },
  {
    id: 73,
    title: "跳系列新作《跳高高2》一把横扫3950倍派彩",
    pic: {
      url: "https://",
      img: "promotion/video/qgeeFPDH.png",
    },
    url: {
      link: "promotion/video/etnqRO3y.mp4",
      domain: "https://",
    },
    internal: true,
    status: true,
    site: ["common", "GPK", "GT", "LEBO", "OG", "LEBO-CG"],
    edited_by: "steve",
    created_at: "2021-06-21T03:34:25-04:00",
    updated_at: "2021-12-16T22:34:30-04:00",
  },
  {
    id: 179,
    title: "大罗神仙也挡不住的3300倍诱惑，希腊众神都来了你还不试试？",
    pic: {
      url: "https://",
      img: "promotion/video_img/iJIVCSMG.PNG",
    },
    url: {
      link: "promotion/video/Jsw34O9a/index.m3u8",
      domain: "https://",
    },
    internal: true,
    status: true,
    site: ["GPK", "GT", "LEBO", "OG", "LEBO-CG", "common"],
    edited_by: "Iris",
    created_at: "2022-04-13T04:43:22-04:00",
    updated_at: "2022-05-10T04:21:38-04:00",
  },
  {
    id: 43,
    title: "【有片】五连线搭三颗鸡蛋 这次总该我赢了吧",
    pic: {
      url: "https://",
      img: "",
    },
    url: {
      link: "promotion/video/nugT6vmk.mp4",
      domain: "https://",
    },
    internal: true,
    status: false,
    site: ["GPK", "GT", "LEBO", "OG", "LEBO-CG", "common"],
    edited_by: "Hana",
    created_at: "2020-12-25T02:07:19-04:00",
    updated_at: "2021-12-16T22:34:30-04:00",
  },
];

export const activeData = [
  {
    id: 21,
    title: "中國周年慶龍虎榜",
    url: "youtube.com/",
    status: true,
    site: ["GPK", "GT", "LEBO", "OG", "LEBO-CG", "common"],
    edited_by: "Finn",
    created_at: "2022-04-13T21:43:34-04:00",
    updated_at: "2022-04-13T21:43:34-04:00",
  },
  {
    id: 20,
    title: "中國春神龍虎榜",
    url: "youtube.com/",
    status: false,
    site: [],
    edited_by: "Finn",
    created_at: "2022-03-03T02:06:52-04:00",
    updated_at: "2022-04-13T21:43:02-04:00",
  },
  {
    id: 19,
    title: "中國新春龍虎榜(GT)",
    url: "youtube.com/",
    status: false,
    site: [],
    edited_by: "Finn",
    created_at: "2022-02-09T02:09:48-04:00",
    updated_at: "2022-03-03T02:06:26-04:00",
  },
  {
    id: 12,
    title: "端午龍虎榜",
    url: "youtube.com/",
    status: false,
    site: [],
    edited_by: "Finn",
    created_at: "2021-05-16T23:37:41-04:00",
    updated_at: "2021-09-08T02:45:40-04:00",
  },
];

export const adfloatData = [
  {
    id: 1,
    title: "冬至龍虎榜",
    status: true,
    site: ["GPK", "GT", "LEBO", "OG", "LEBO-CG", "common"],
    url: "",
    sort: 0,
    pic: {
      img: "promotion/ad_float/Ukk5zzml.png",
      url: "https://",
    },
    link_id: 2,
    lang: "cn",
    edited_by: "Finn",
    start_time: "2021-12-08T00:00:00-04:00",
    end_time: "2032-12-08T00:00:00-04:00",
    created_at: "2021-12-08T22:27:46-04:00",
    updated_at: "2022-01-19T23:39:35-04:00",
  },
  {
    id: 18,
    title: "中國春神龍虎榜",
    status: true,
    site: [],
    url: "",
    sort: 0,
    pic: {
      img: "promotion/ad_float/VIeyiawv.png",
      url: "https://",
    },
    link_id: 6,
    lang: "cn",
    edited_by: "Finn",
    start_time: "2022-03-03T00:00:00-04:00",
    end_time: "2022-04-15T00:00:00-04:00",
    created_at: "2022-03-03T02:09:32-04:00",
    updated_at: "2022-04-13T21:43:52-04:00",
  },
  {
    id: 17,
    title: "元宵押碼王",
    status: false,
    site: ["GT"],
    url: "",
    sort: 1,
    pic: {
      img: "promotion/ad_float/c6EZxMgX.png",
      url: "https://",
    },
    link_id: 2,
    lang: "cn",
    edited_by: "Finn",
    start_time: "2022-02-09T00:00:00-04:00",
    end_time: "2042-02-09T00:00:00-04:00",
    created_at: "2022-02-09T02:07:59-04:00",
    updated_at: "2022-03-03T02:09:36-04:00",
  },
];

export const adpopData = [
  {
    id: 67,
    title: "中國周年慶龍虎榜",
    url: "",
    status: true,
    pic: {
      img: "promotion/ad_popup/sAeNNbfM.jpg",
      url: "https://",
    },
    site: ["GPK", "GT", "LEBO", "OG", "LEBO-CG", "common"],
    link_id: 2,
    lang: "cn",
    edited_by: "Finn",
    created_at: "2022-04-13T21:46:11-04:00",
    updated_at: "2022-04-13T21:46:11-04:00",
  },
  {
    id: 66,
    title: "中國春神龍虎榜",
    url: "",
    status: false,
    pic: {
      img: "promotion/ad_popup/cYJ2Zuse.jpg",
      url: "https://",
    },
    site: [],
    link_id: 6,
    lang: "cn",
    edited_by: "Finn",
    created_at: "2022-03-03T02:10:06-04:00",
    updated_at: "2022-03-03T02:10:06-04:00",
  },
  {
    id: 64,
    title: "中國新春龍虎榜",
    url: "",
    status: true,
    pic: {
      img: "promotion/ad_popup/6GoE5WC5.jpg",
      url: "https://",
    },
    site: ["GPK", "GT", "LEBO", "OG", "LEBO-CG", "common"],
    link_id: 2,
    lang: "cn",
    edited_by: "Finn",
    created_at: "2022-01-19T23:39:12-04:00",
    updated_at: "2022-01-19T23:39:12-04:00",
  },
  {
    id: 6,
    title: "遊戲攻略-武圣",
    url: "./#/game-guides/guides-content/31",
    status: true,
    pic: {
      img: "promotion/ad_popup/ekGNlVGY.png",
      url: "https://",
    },
    site: ["LEBO", "GPK", "GT", "OG", "LEBO-CG", "common"],
    link_id: 3,
    lang: "cn",
    edited_by: "Iris",
    created_at: "2020-07-09T02:09:55-04:00",
    updated_at: "2020-07-09T02:09:55-04:00",
  },
];

export const htmlData = [
  {
    html: {
      all: {
        dom: "",
        script: "",
      },
      home: {
        dom: "",
        script: "",
      },
    },
    status: {
      all: false,
      home: false,
    },
    site: "GPK",
    edited_by: "Aaron",
    created_at: "2022-01-07T03:46:13-04:00",
    updated_at: "2022-01-27T03:20:47-04:00",
  },
  {
    html: {
      all: {
        dom: "no data",
        script:
          '<link rel="alternate" hreflang="x-default" href="https://site.cq9gaming.com" />\n<link rel="alternate" hreflang="zh-Hans" href="https://site.cq9gaming.com"/>\n<link rel="alternate" hreflang="vi" href="https://site.cq9gaming.com/vn"/>\n<link rel="alternate" hreflang="th" href="https://site.cq9gaming.com/th"/>',
      },
    },
    status: {
      all: true,
    },
    site: "common",
    edited_by: "Aaron",
    created_at: "2022-01-27T03:21:01-04:00",
    updated_at: "2022-01-27T03:28:15-04:00",
  },
];
